<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Admin View</title>
</head>
<body>
	<%
		String username = request.getParameter("username");
		if(username == null)
			request.getRequestDispatcher(("welcomePage.jsp")).forward(request, response);
		session.setAttribute("username", username);
			
	%>
	
	
	<p> Admin View for <strong> <%= username %> </strong></p>
	<strong>Edit User</strong>
	<br>
		<form method="get" action="editRep.jsp">
			<table>
				<tr>
					<td>Enter Username (req)</td><td><input type="text" name="username"></td>
				</tr>
				<tr>    
					<td>Set Username (optional)</td><td><input type="text" name="newUsername"></td>
				</tr>
				<tr>
					<td>Set First Name (req)</td><td><input type="text" name="firstName"></td>
				</tr>
				<tr>
					<td>Set Last Name (req)</td><td><input type="text" name="lastName"></td>
				</tr>
				<tr>
					<td>Set Password (req)</td><td><input type="text" name="password"></td>
				</tr>
				<tr>
					<td>Set Role (req)(Customer, Representative)</td><td><input type="text" name="role"></td>
				</tr>
			</table>
			<input type="submit" value="Edit user info">
		</form>
	<br>
	<strong>Add User</strong>
	<br>
		<form method="get" action="addUser.jsp">
			<table>
				<tr>
					<td>Enter Username (req)</td><td><input type="text" name="username"></td>
				</tr>
				<tr>
					<td>First Name (req)</td><td><input type="text" name="firstName"></td>
				</tr>
				<tr>
					<td>Last Name (req)</td><td><input type="text" name="lastName"></td>
				</tr>
				<tr>
					<td>Password (req)</td><td><input type="text" name="password"></td>
				</tr>
				<tr>
					<td>Role (req)(Customer, Representative)</td><td><input type="text" name="role"></td>
				</tr>
			</table>
			<input type="submit" value="Add user">
		</form>
	<br>
	<strong>Delete User</strong>
	<br>
		<form method="get" action="delUser.jsp">
			<table>
				<tr>
					<td>Enter Username (req)</td><td><input type="text" name="username"></td>
				</tr>
			</table>
			<input type="submit" value="Delete user">
		</form>
	<br>
	<strong>Monthly Sales Report</strong>
	<br>
		<form method="post" action="salesReport.jsp">
		  <input type="radio" name="command" value="1"/>View January Sales Report
		  <br>
		  <input type="radio" name="command" value="2"/>View February Sales Report
		  <br>
		  <input type="radio" name="command" value="3"/>View March Sales Report
		  <br>
		  <input type="radio" name="command" value="4"/>View April Sales Report
		  <br>
		  <input type="radio" name="command" value="5"/>View May Sales Report
		  <br>
		  <input type="radio" name="command" value="6"/>View June Sales Report
		  <br>
		  <input type="radio" name="command" value="7"/>View July Sales Report
		  <br>
		  <input type="radio" name="command" value="8"/>View August Sales Report
		  <br>
		  <input type="radio" name="command" value="9"/>View September Sales Report
		  <br>
		  <input type="radio" name="command" value="10"/>View October Sales Report
		  <br>
		  <input type="radio" name="command" value="11"/>View November Sales Report
		  <br>
		  <input type="radio" name="command" value="12"/>View December Sales Report
		  <br>
		  <input type="submit" value="submit" />
		</form>
	<br>
	<strong>List Reservations by Flight Number</strong>
	<br>
		<form method="get" action="listReservationsFlightNum.jsp">
			<table>
				<tr>
					<td>Enter Flight Number (req)</td><td><input type="text" name="fNum"></td>
				</tr>
			</table>
			<input type="submit" value="Search">
		</form>
	<br>
	<strong>List Reservations by Customer Username</strong>
	<br>
		<form method="get" action="listReservationsName.jsp">
			<table>
				<tr>
					<td>Enter Customer Username (req)</td><td><input type="text" name="name"></td>
				</tr>
			</table>
			<input type="submit" value="Search">
		</form>
	<br>
	<strong>List Revenue Generated By Flight</strong>
	<br>
		<form method="get" action="revGenByFlight.jsp">
			<table>
				<tr>
					<td>Enter Flight (req)</td><td><input type="text" name="flight"></td>
				</tr>
			</table>
			<input type="submit" value="Find Revenue">
		</form>
	<br>
	<strong>List Revenue Generated By Airline</strong>
	<br>
		<form method="get" action="revGenByAirline.jsp">
			<table>
				<tr>
					<td>Enter Airline (req)</td><td><input type="text" name="flight"></td>
				</tr>
			</table>
			<input type="submit" value="Find Revenue">
		</form>
	<br>
	<strong>List Revenue Generated By Customer</strong>
	<br>
		<form method="get" action="revGenByCustomer.jsp">
			<table>
				<tr>
					<td>Enter Username (req)</td><td><input type="text" name="flight"></td>
				</tr>
			</table>
			<input type="submit" value="Find Revenue">
		</form>
	<br>
	<strong>Customer With Most Total Revenue Generated</strong>
	<br>
		<form method="get" action="findMostRevGen.jsp">
			<input type = "submit" value = "Find Customer">
		</form>
	<br>
	<strong>Most Active Flights</strong>
	<br>
		<form method="get" action="findMostActiveFlights.jsp">
			<input type = "submit" value = "Search">
		</form>
	<br>
	
	<form method="post" action="welcomePage.jsp">
		<input type="submit" value="logout">
	</form>
</body>
</html>